Traceback (most recent call last):
  File "traceback.py", line 10, in <module>
    undefined_function()
NameError: name 'undefined_function' is not defined